# Generated by Django 3.2.9 on 2021-12-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('SKU_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Product_Name', models.CharField(max_length=50)),
                ('QTY', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
    ]
